---
title: "Sank Freaking Sanity"
author: "Travis Weber"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
```

## Include statements

```{r}
library(reshape)
library(tidyr)
library(ggplot2)
library(ggalluvial)
library(alluvial)
library(plyr)
library(dplyr)
library(cluster)
source("./04_analysis/02_protocol/Utils.r")
```

## Data import


```{r}
source("./04_analysis/01_input/setup.r")
binaryAttrs <- read.csv("./04_analysis/01_input/BinaryAttrs.csv") %>%
  dplyr::rename(filename = binary)
```

## Clustering

### Defining Helper functions
```{r}
clust_and_title <- function(col) {
  clust <- pam(col, 3)
  clust_titles(clust)
}


clust_and_title_alt <- function(col) {
  alt_names = factor(c("small", "mid", "large"), levels=c("large", "mid", "small"))
  clust <- pam(col, 3)
  clust_titles(clust, names = alt_names)
}
```
### Cluster By Version
```{r pressure, echo=FALSE}
cve_version_clusters <- cve_bin %>% 
  mutate_if(
    is.numeric, 
    clust_and_title
  ) %>%
  rename_with(~ gsub("version_", "cve_cluster_", .x))

cwe_checker_version_clusters <- cwe_checker %>% 
  mutate_if(
    is.numeric, 
    clust_and_title
  ) %>%
  rename_with(~ gsub("version_", "cwe_cluster_", .x))
```
### Cluster by binary size
```{r}
alt_names = factor(c("small", "mid", "large"), levels=c("large", "mid", "small"))
binaryAttrs <- binaryAttrs %>% mutate(size_cluster = clust_and_title_alt(size))
```

### Visually double check Cluster labels

#### Prep data
```{r}
cve_bin_long_clusts <- left_join(cve_bin_long, cve_version_clusters) %>%
  left_join(binaryAttrs)

cwe_checker_clusts <- left_join(cwe_checker_long, cwe_checker_version_clusters) %>%
  left_join(binaryAttrs)
```

#### Visuals for cwe checker
```{r}
cwe_checker_clusts %>% ggplot( mapping = aes(x = version, y = vuln_count)) +
  geom_line(mapping = aes(group = filename, color = cwe_cluster_0.4), size = 2, alpha = 0.5) +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  xlab("Version") +
  facet_grid(cols = vars(cwe_cluster_0.4)) +
  theme(legend.position = "top") +
  scale_fill_brewer(type = "qual")

cwe_checker_clusts %>% ggplot( mapping = aes(x = version, y = vuln_count)) +
  geom_line(mapping = aes(group = filename, color = cwe_cluster_0.5), size = 2, alpha = 0.5) +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  xlab("Version") +
  facet_grid(cols = vars(cwe_cluster_0.5)) +
  theme(legend.position = "top") +
  scale_fill_brewer(type = "qual")

cwe_checker_clusts %>% ggplot( mapping = aes(x = version, y = vuln_count)) +
  geom_line(mapping = aes(group = filename, color = cwe_cluster_0.6), size = 2, alpha = 0.5) +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  xlab("Version") +
  facet_grid(cols = vars(cwe_cluster_0.6)) +
  theme(legend.position = "top") +
  scale_fill_brewer(type = "qual")

cwe_checker_clusts %>% ggplot(aes(x = version, y = vuln_count, color = size_cluster)) + geom_line(mapping = aes(group = filename))
```

#### Visuals for CVE BIN Tool
```{r}
cve_bin_long_clusts %>% ggplot( mapping = aes(x = version, y = vuln_count)) +
  geom_line(mapping = aes(group = filename, color = cve_cluster_1.0), size = 2, alpha = 0.5) +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  xlab("Version") +
  facet_grid(cols = vars(cve_cluster_1.0)) +
  theme(legend.position = "top") +
  scale_fill_brewer(type = "qual")

cve_bin_long_clusts %>% ggplot( mapping = aes(x = version, y = vuln_count)) +
  geom_line(mapping = aes(group = filename, color = cve_cluster_2.1), size = 2, alpha = 0.5) +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  xlab("Version") +
  facet_grid(cols = vars(cve_cluster_2.1)) +
  theme(legend.position = "top") +
  scale_fill_brewer(type = "qual")

cve_bin_long_clusts %>% ggplot( mapping = aes(x = version, y = vuln_count)) +
  geom_line(mapping = aes(group = filename, color = cve_cluster_3.1.1), size = 2, alpha = 0.5) +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  xlab("Version") +
  facet_grid(cols = vars(cve_cluster_3.1.1)) +
  theme(legend.position = "top") +
  scale_fill_brewer(type = "qual")

cve_bin_long_clusts %>% ggplot(aes(x = version, y = vuln_count, color = size_cluster)) + geom_line(mapping = aes(group = filename))
```

### Cluster by size of binary
```{r}
alt_names = factor(c("small", "mid", "large"), levels=c("large", "mid", "small"))
binaryAttrs <- binaryAttrs %>% mutate(size_cluster = clust_and_title_alt(size))
```

## Sankeys

### combine data
```{r}
all_together_now <- left_join(cve_version_clusters, cwe_checker_version_clusters) %>% left_join(binaryAttrs)
```

### sankification function
```{r}
sankey <- function(columns) {
  columns <- c(columns, "filename")
  
 all_together_now %>%
    select(!size) %>%
    select(any_of(columns)) %>%
    mutate_all(as.factor) %>%
    pivot_longer(
      cols = !filename,
      names_to = "sank_column",
      values_to = "group"
    ) %>%
    mutate(sank_column = factor(sank_column, levels = columns)) %>%
    ggplot(aes(x = sank_column, stratum = group, alluvium = filename,
           fill = group, label = group)) +
    geom_flow(stat = "alluvium", lode.guidance = "frontback") +
    geom_stratum() +
    theme(
      legend.position = "bottom",
      text = element_text(size = 12),
      axis.text = element_text(size = 10),
      axis.text.x = element_text(angle = 40, hjust=1)
    )
}
```

### Go to town
```{r}
sankey(c("cve_cluster_1.0", "cve_cluster_2.1", "cve_cluster_3.1.1"))
sankey(c("cwe_cluster_0.4", "cwe_cluster_0.5", "cwe_cluster_0.6"))
```