---
title: "Sank Freaking Sanity"
author: "Travis Weber"
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(message = FALSE)
```

## Include statements

```{r}
library(reshape)
library(tidyr)
library(ggplot2)
library(ggalluvial)
library(alluvial)
library(plyr)
library(dplyr)
library(cluster)
# setwd("/home/amr/Documents/Research/CyberQA/REU_2022/toolEvoAMR/tool-evolution")
# source("./04_analysis/02_protocol/Utils.r")



### run toolEvo_versionEffects.R first...
```

## Data import


```{r}
source("./04_analysis/01_input/setup.r")
# binaryAttrs <- read.csv("./04_analysis/01_input/BinaryAttrs.csv") %>%
#   dplyr::rename(filename = binary)

cwe_check_wide <- cwe_checker
cve_bin_wide <- cve_bin
binary_attr <- read.csv("./04_analysis/01_input/BinaryAttrs.csv")

## wrangling
dim(binary_attr)
dim(cwe_check_wide)
dim(cve_bin_wide)

#############
# something is weird with the names of the binary files in this new cwe checker dataset
cwe_check_wide$filename[!(cwe_check_wide$filename %in% binary_attr$binary)]
binary_attr$binary[!(binary_attr$binary %in% cwe_check_wide$filename)]
#############

## trying removing periods and dashes in the filenames
cwe_check_wide$filename <-
  cwe_check_wide$filename %>%
  str_remove_all("[.]") %>%
  str_remove_all("[-]") %>%
  str_remove_all("[_]")

cve_bin_wide$filename <-
  cve_bin_wide$filename %>%
  str_remove_all("[.]") %>%
  str_remove_all("[-]") %>%
  str_remove_all("[_]")

binary_attr$binary <-
  binary_attr$binary %>%
  str_remove_all("[.]") %>%
  str_remove_all("[-]") %>%
  str_remove_all("[_]")


# shorten findings dataset to only those binaries for which we have attributes
cwe_check_wide <- cwe_check_wide[cwe_check_wide$filename %in% binary_attr$binary,]
cve_bin_wide <- cve_bin_wide[cve_bin_wide$filename %in% binary_attr$binary,]

# check to see that the same set of binaries was assessed by both tools
identical(sort(cve_bin_wide$filename), sort(cwe_check_wide$filename))

# subset to the shorter list of binaries
dim(cwe_check_wide)
dim(cve_bin_wide)

sum(!(cwe_check_wide$filename %in% cve_bin_wide$filename))  # all the cwe checker binary names are in the cve bin names
sum(!(cwe_check_wide$filename %in% binary_attr$binary))  # all the cwe checker binary names are in the attribute bin names


# shorten attributes to only those where we have findings (only need to check
# against one tool since they assessed the same suite of binaries)
binary_attr <- binary_attr[binary_attr$binary %in% cwe_check_wide$filename, ]
cve_bin_wide <- cve_bin_wide[cve_bin_wide$filename %in% cwe_check_wide$filename, ]

# order each data frame by the name of the binaries
cwe_check_wide <- cwe_check_wide[order(cwe_check_wide$filename), ]
cve_bin_wide <- cve_bin_wide[order(cve_bin_wide$filename), ]
binary_attr <- binary_attr[order(binary_attr$binary), ]

identical(cwe_check_wide$filename, binary_attr$binary)
identical(cve_bin_wide$filename, binary_attr$binary)

row.names(cwe_check_wide) <- cwe_check_wide$filename
row.names(cve_bin_wide) <- cve_bin_wide$filename

names(binary_attr)[names(binary_attr) == "binary"] <- "filename"

# drop all columns that we don't need
cwe_check_wide <- ( cwe_check_wide[, ! (names(cwe_check_wide) %in% c("X") )] )
cve_bin_wide <- ( cve_bin_wide[, !(names(cve_bin_wide) %in% c("X") )] )

cwe_check_long <-
  pivot_longer(
    data = cwe_check_wide,
    cols = starts_with("version"),
    names_to = "version",
    values_to = "findings_count"
    )

cve_bin_long <-
  pivot_longer(
    data = cve_bin_wide,
    cols = starts_with("version"),
    names_to = "version",
    values_to = "findings_count"
  )
```

## Clustering

### Defining Helper functions
```{r}
clust_and_title <- function(col) {
  clust <- pam(col, 3)
  clust_titles(clust)
}


clust_and_title_alt <- function(col) {
  alt_names = factor(c("small", "mid", "large"), levels=c("large", "mid", "small"))
  clust <- pam(col, 3)
  clust_titles(clust, names = alt_names)
}
```
### Cluster By Version
```{r pressure, echo=FALSE}
cve_version_clusters <- cve_bin_wide %>% 
  mutate_if(
    is.numeric, 
    clust_and_title
  ) %>%
  rename_with(~ gsub("version_", "cve_cluster_", .x))

cwe_checker_version_clusters <- cwe_checker_wide %>% 
  mutate_if(
    is.numeric, 
    clust_and_title
  ) %>%
  rename_with(~ gsub("version_", "cwe_cluster_", .x))
```
### Cluster by binary size
```{r}
alt_names = factor(c("small", "mid", "large"), levels=c("large", "mid", "small"))
binary_attr <- binary_attr %>% mutate(size_cluster = clust_and_title_alt(size))
```

### Visually double check Cluster labels

#### Prep data
```{r}
cve_bin_long_clusts <- left_join(cve_bin_long, cve_version_clusters) %>%
  left_join(binary_attr)

cwe_checker_clusts <- left_join(cwe_check_long, cwe_checker_version_clusters) %>%
  left_join(binary_attr)
```

#### Visuals for cwe checker
```{r}
cwe_checker_clusts %>% ggplot( mapping = aes(x = version, y = findings_count)) +
  geom_line(mapping = aes(group = filename, color = cwe_cluster_0.4), size = 2, alpha = 0.5) +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  xlab("Version") +
  facet_grid(cols = vars(cwe_cluster_0.4)) +
  theme(legend.position = "top") +
  scale_fill_brewer(type = "qual")

cwe_checker_clusts %>% ggplot( mapping = aes(x = version, y = findings_count)) +
  geom_line(mapping = aes(group = filename, color = cwe_cluster_0.5), size = 2, alpha = 0.5) +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  xlab("Version") +
  facet_grid(cols = vars(cwe_cluster_0.5)) +
  theme(legend.position = "top") +
  scale_fill_brewer(type = "qual")

cwe_checker_clusts %>% ggplot( mapping = aes(x = version, y = findings_count)) +
  geom_line(mapping = aes(group = filename, color = cwe_cluster_0.6), size = 2, alpha = 0.5) +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  xlab("Version") +
  facet_grid(cols = vars(cwe_cluster_0.6)) +
  theme(legend.position = "top") +
  scale_fill_brewer(type = "qual")

cwe_checker_clusts %>% ggplot(aes(x = version, y = findings_count, color = size_cluster)) + geom_line(mapping = aes(group = filename))
```

#### Visuals for CVE BIN Tool
```{r}
cve_bin_long_clusts %>% ggplot( mapping = aes(x = version, y = findings_count)) +
  geom_line(mapping = aes(group = filename, color = cve_cluster_1.0), size = 2, alpha = 0.5) +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  xlab("Version") +
  facet_grid(cols = vars(cve_cluster_1.0)) +
  theme(legend.position = "top") +
  scale_fill_brewer(type = "qual")

cve_bin_long_clusts %>% ggplot( mapping = aes(x = version, y = findings_count)) +
  geom_line(mapping = aes(group = filename, color = cve_cluster_2.1), size = 2, alpha = 0.5) +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  xlab("Version") +
  facet_grid(cols = vars(cve_cluster_2.1)) +
  theme(legend.position = "top") +
  scale_fill_brewer(type = "qual")

cve_bin_long_clusts %>% ggplot( mapping = aes(x = version, y = findings_count)) +
  geom_line(mapping = aes(group = filename, color = cve_cluster_3.1.1), size = 2, alpha = 0.5) +
  scale_x_discrete(guide = guide_axis(angle = 90)) +
  xlab("Version") +
  facet_grid(cols = vars(cve_cluster_3.1.1)) +
  theme(legend.position = "top") +
  scale_fill_brewer(type = "qual")

cve_bin_long_clusts %>% ggplot(aes(x = version, y = findings_count, color = size_cluster)) + geom_line(mapping = aes(group = filename))
```

### Cluster by size of binary
```{r}
alt_names = factor(c("small", "mid", "large"), levels=c("large", "mid", "small"))
binary_attr <- binary_attr %>% mutate(size_cluster = clust_and_title_alt(size))
```

## Sankeys

### combine data
```{r}
all_together_now <- left_join(cve_version_clusters, cwe_checker_version_clusters) %>% left_join(binary_attr)
```

### sankification function
```{r}
sankey <- function(columns, inputDataFrame = all_together_now) {
  columns <- c(columns, "filename")
  
 inputDataFrame %>%
    select(!size) %>%
    select(any_of(columns)) %>%
    mutate_all(as.factor) %>%
    pivot_longer(
      cols = !filename,
      names_to = "sank_column",
      values_to = "group"
    ) %>%
    mutate(sank_column = factor(sank_column, levels = columns)) %>%
    ggplot(aes(x = sank_column, stratum = group, alluvium = filename,
           fill = group, label = group)) +
    geom_flow(stat = "alluvium", lode.guidance = "frontback") +
    geom_stratum() +
    theme(
      legend.position = "bottom",
      text = element_text(size = 12),
      axis.text = element_text(size = 10),
      axis.text.x = element_text(angle = 40, hjust=1)
    )
}
```

### Go to town
```{r}
sankey(c("cve_cluster_1.0", "cve_cluster_2.1", "cve_cluster_3.1.1"))
sankey(c("cwe_cluster_0.4", "cwe_cluster_0.5", "cwe_cluster_0.6"))
```
