---
title: "Findings"
author: "Travis Weber, Colleen Lemak"
date: "`r Sys.Date()`"
output: pdf_document
---

# Research Findings

Import requirements

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r}
library(tidyverse)
library(rjson)
library(gplots)
```

## Import input data (cve bin tool)

Importing and standardizing data for CVE bin tool

```{r}
cve_bin <- read.csv("./02_wrangling/04_product/cve_bin_tool_wide_1658175857.csv 
")
cve_bin_long <- read.csv("./02_wrangling/04_product/cve_bin_tool_long_1658175857.csv 
")
```

## CWE Checker Data import

```{r}
cwe_checker <- fromJSON(file = "../cwe_checker/output_statistics/version_results/parsed_results.json") %>%
  lapply(as.data.frame) %>%
  do.call(rbind,.)

cwe_checker$filename <- row.names(cwe_checker)
names(cwe_checker) <- gsub('X', 'version_', names(cwe_checker))

version_dates <- data.frame(version_0.6 = '2022-06-10', version_0.5 = '2021-07-05', version_0.4 = '2021-01-07') %>%
  t() %>%
  as.data.frame()


names(version_dates)[names(version_dates) == 'V1'] <- 'date'
version_dates$version <- row.names(version_dates)
as.Date(version_dates$date)

cwe_checker_long <- pivot_longer(cwe_checker, !filename, names_to = "version", values_to = "vuln_count") %>%
  left_join(version_dates)
```

## Graphing Averages Over time

```{r}
cve_bin_long %>% ggplot(aes(x = date, y=vuln_count)) +
    ggtitle("CVE bin tool (no v3.1, .1 alpha)") +
    geom_line(mapping = aes(group = filename), color="black", alpha=0.1, size=2)


cwe_checker_long %>% ggplot(mapping = aes(x = version, y = vuln_count))+
  geom_line(mapping = aes(group = filename), color = 'black', alpha = 0.1, size = 2)+
  ggtitle('CWE_CHECKER Vulnerabilities per version')
```

## Binary Heat Map

```{r}
my_palette <- colorRampPalette(c("red", "white", "black"))(n = 299)

cve_bin %>% mutate_if(is.numeric, ~(scale(.) %>% as.vector)) %>%
  # sort by vulnerabilities in first version
  arrange(desc(version_3.1.1)) %>% 
  # remove filename column
  select(-starts_with("filename")) %>% 
  as.matrix() %>% 
  heatmap.2(Rowv = F, Colv = F, tracecol = NA, col=my_palette, labRow = F)

cwe_checker %>% mutate_if(is.numeric, ~(scale(.) %>% as.vector)) %>%
  # sort by vulnerabilities in first version
  arrange(desc(version_0.6)) %>% 
  rev() %>%
  # remove filename column
  select(-starts_with("filename")) %>% 
  as.matrix() %>% 
  heatmap.2(Rowv = F, Colv = F, tracecol = NA, col=my_palette, labRow = F)
```

## Exploring stability of not being zero

### Heat map

```{r}
cve_bin_long %>% within(is_zero <- vuln_count == 0) %>%
  ggplot(mapping = aes(x = version, y = reorder(filename, is_zero), fill = is_zero)) +
    geom_tile() +
    theme(
      axis.text.y=element_blank()
    ) +
    scale_fill_manual(values=c("FALSE"="firebrick", "TRUE"="dodgerblue"))

cwe_checker_long %>% within(is_zero <- vuln_count == 0) %>%
  ggplot(mapping = aes(x = version, y = reorder(filename, is_zero), fill = is_zero)) +
    geom_tile() +
    theme(
      axis.text.y=element_blank()
    ) +
    scale_fill_manual(values=c("FALSE"="firebrick", "TRUE"="dodgerblue"))
```

### Bar Chart

```{r}
cve_bin %>% select(starts_with("version")) %>% 
  apply(2, function(c) c!=0) %>%
  apply(2, sum) %>% 
  tibble(version = names(.), not_zero = .) %>%
  ggplot(mapping = aes(x=version, y = not_zero)) +
    geom_bar(stat = 'identity')

cwe_checker %>% select(starts_with("version")) %>% 
  apply(2, function(c) c!=0) %>%
  apply(2, sum) %>% 
  tibble(version = names(.), not_zero = .) %>%
  ggplot(mapping = aes(x=version, y = not_zero)) +
    geom_bar(stat = 'identity')
```
